name: "Report Workflow Jobs statuses"
description: "Write a JUnit XML Report for Workflow Jobs statuses"

inputs:
  github_token:
    description: "GITHUB_TOKEN"
    required: true

  report_path:
    description: "File path of a generated XML report, used for reading failing test cases"
    default: "./workflow-results/"

  report_filename:
    description: "Filename of a generated XML report"
    default: "workflow-jobs.xml"

runs:
  using: "node12"
  main: "dist/index.js"
